# Generated by cpp11: do not edit by hand

bilinear_c <- function(x_breaks, y_breaks, grid, x, y) {
  .Call(`_particles_bilinear_c`, x_breaks, y_breaks, grid, x, y)
}

collision_c <- function(pos, vel, radii, strength) {
  .Call(`_particles_collision_c`, pos, vel, radii, strength)
}

nbody_c <- function(pos, strength, theta, min_dist, max_dist, alpha) {
  .Call(`_particles_nbody_c`, pos, strength, theta, min_dist, max_dist, alpha)
}

points_to_path_c <- function(pos, path, close) {
  .Call(`_particles_points_to_path_c`, pos, path, close)
}

points_to_lines_c <- function(line1, line2, point) {
  .Call(`_particles_points_to_lines_c`, line1, line2, point)
}

angle_diff_c <- function(a, b) {
  .Call(`_particles_angle_diff_c`, a, b)
}
