# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collision <- function(pos, vel, radii, strength) {
    .Call('particles_collision', PACKAGE = 'particles', pos, vel, radii, strength)
}

nbody <- function(pos, strength, theta, min_dist, max_dist, alpha) {
    .Call('particles_nbody', PACKAGE = 'particles', pos, strength, theta, min_dist, max_dist, alpha)
}

